name: build devnet docker image

on:
  workflow_dispatch:
    inputs:
      subtensor_repo_ref:
        description: 'A git ref of the subtensor repo (tag/branch/commit-hash)'
        default: 'main'
        type: string

env:
  IMAGE_NAME: "backenddevelopersltd/compute-horde-local-subtensor:v0-latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make more space
        run: rm -rf /opt/hostedtoolcache

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}
          build-args: |
            SUBTENSOR_REPO_REF=${{ inputs.subtensor_repo_ref }}
